services:
  postgresql:
    image: postgres:15
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - python
      - kind

volumes:
  db_data:

networks:
  python:
  kind:
    external: true
